### ISSUE TITLE
Add a Bottom Navigation Bar

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#21] opened 2020-03-01 08:18 UTC
Remove the Existing Drawer and Replace it with a stylized modern looking bottom navigation bar  with appropriate Icons .
Add the following items:
-  Home
- Events
- Projects
- About Us

**Comment by himanshusharma89** [comment] 2020-03-01 08:23
Assign me this issue

**Comment by vishakha2108** [comment] 2020-03-01 08:26
I would like to work on this

**Comment by voldemortuk** [comment] 2020-03-01 08:33
I would like to work on this issue

**Comment by AjinkyaTaranekar** [comment] 2020-03-01 09:09
I would like to work on this issue. Moreover, I suggest the following design, for bottom navigation.
image
![image](https://user-images.githubusercontent.com/44701159/75622819-7d2f6180-5bca-11ea-82b5-8ae962aecdb3.png)

**Comment by smaranjitghose** [comment] 2020-03-01 09:19
@Valdermaut  Go forward

**Comment by puneethkanna** [comment] 2020-03-02 19:13
I had prepared a navigation bar, can I work on it.

**Comment by smaranjitghose** [comment] 2020-03-02 19:34
If you  wish..make a pull request..however  it shall be considered  once the currently assigned  mentees work gets merged  after review from mentors

**Comment by vinay2214** [comment] 2020-03-04 15:59
I would like to work on it iam a android developer.

**Comment by puneethkanna** [comment] 2020-03-08 02:19
> If you wish..make a pull request..however it shall be considered once the currently assigned mentees work gets merged after review from mentors

Sir, the PR has been merged, so the issue is closed. If needed it should be reopened to improve it.

**Closed as completed** 2020-03-10 06:09 UTC
Labels: gssoc20, easy
